# Generated by Django 5.2.11 on 2026-02-27 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Height in cm', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='weight_kg',
            field=models.DecimalField(blank=True, decimal_places=1, help_text='Weight in kg', max_digits=5, null=True),
        ),
    ]
