# Generated by Django 5.2.11 on 2026-03-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_height_cm_student_weight_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='follow_nutrition',
            field=models.BooleanField(default=False, help_text='Client agrees to follow nutrition recommendations'),
        ),
        migrations.AddField(
            model_name='student',
            name='intake_status',
            field=models.CharField(choices=[('active', 'Active'), ('pending', 'Pending review')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='training_days_per_week',
            field=models.PositiveSmallIntegerField(blank=True, help_text='How many days per week the client can train', null=True),
        ),
    ]
