# Generated by Django 5.2.11 on 2026-03-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_add_intake_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='blood_analysis',
            field=models.JSONField(blank=True, help_text='Cached AI blood test analysis', null=True),
        ),
    ]
