# Generated by Django 5.2.11 on 2026-03-06 23:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0006_add_blood_analysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='invite_token',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_plan',
            field=models.CharField(choices=[('monthly', 'Monthly (2 programs)'), ('3months', '3 Months (6 programs)')], default='monthly', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student', to=settings.AUTH_USER_MODEL),
        ),
    ]
