# Generated by Django 5.2.11 on 2026-03-11 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_student_invite_token_student_payment_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='photo_analysis',
            field=models.TextField(blank=True, help_text='Cached AI photo analysis'),
        ),
    ]
