# Generated by Django 5.2.11 on 2026-03-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_add_photo_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_handle',
            field=models.CharField(blank=True, help_text='Venmo @handle, PayPal email/link, etc.', max_length=200),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('venmo', 'Venmo'), ('paypal', 'PayPal'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('other', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('pending', 'Payment Pending'), ('overdue', 'Overdue')], max_length=20),
        ),
    ]
