# Generated by Django 5.2.11 on 2026-03-11 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0009_add_payment_method_handle_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('specialty', models.CharField(help_text='E.g. Endocrinologist, Hormone Specialist', max_length=200)),
                ('bio', models.TextField(blank=True)),
                ('photo_url', models.URLField(blank=True, max_length=500)),
                ('booking_link', models.URLField(help_text='Your affiliate/referral booking link', max_length=500)),
                ('compensation_note', models.TextField(blank=True, help_text='Private note about referral compensation (only visible to trainer)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='student',
            name='ai_recommendations',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
