# Generated by Django 5.2.11 on 2026-03-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_add_ai_recommendations_and_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainerPaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venmo_handle', models.CharField(blank=True, help_text='Your Venmo @handle (e.g. @YourName)', max_length=200)),
                ('paypal_handle', models.CharField(blank=True, help_text='Your PayPal.me link or email (e.g. paypal.me/YourName)', max_length=200)),
                ('zelle_handle', models.CharField(blank=True, help_text='Your Zelle phone number or email', max_length=200)),
            ],
            options={
                'verbose_name': 'Trainer Payment Settings',
            },
        ),
        migrations.AddField(
            model_name='student',
            name='trainer_recommendation',
            field=models.TextField(blank=True, help_text='Trainer-written recommendation visible to student'),
        ),
        migrations.AddField(
            model_name='student',
            name='trainer_recommendation_confirmed',
            field=models.BooleanField(default=False, help_text='When True, student can see this recommendation'),
        ),
        migrations.AlterField(
            model_name='student',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('venmo', 'Venmo'), ('paypal', 'PayPal'), ('zelle', 'Zelle'), ('cash', 'Cash'), ('bank', 'Bank Transfer'), ('other', 'Other')], max_length=20),
        ),
    ]
