# Generated by Django 5.2.11 on 2026-03-19 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0011_trainerpaymentsettings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='payment_reminder_sent_date',
            field=models.DateField(blank=True, help_text='Last date a payment reminder email was sent', null=True),
        ),
    ]
