# Generated by Django 5.2.11 on 2026-03-06 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0007_student_invite_token_student_payment_plan_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyMeasurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('body_fat_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('waist_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('hips_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('chest_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('arms_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('legs_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='students.student')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
