# Generated by Django 5.2.11 on 2026-03-16 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurements', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bodymeasurement',
            name='arms_cm',
        ),
        migrations.RemoveField(
            model_name='bodymeasurement',
            name='body_fat_pct',
        ),
        migrations.RemoveField(
            model_name='bodymeasurement',
            name='chest_cm',
        ),
        migrations.RemoveField(
            model_name='bodymeasurement',
            name='hips_cm',
        ),
        migrations.RemoveField(
            model_name='bodymeasurement',
            name='legs_cm',
        ),
        migrations.RemoveField(
            model_name='bodymeasurement',
            name='waist_cm',
        ),
    ]
