# Generated by Django 5.2.11 on 2026-02-26 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogram',
            name='nutrition_plan',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutprogram',
            name='training_days',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
