# Generated by Django 5.2.11 on 2026-02-26 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_workoutprogram_nutrition_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programexercise',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='programexercise',
            name='reason_ru',
            field=models.TextField(blank=True),
        ),
    ]
