# Generated by Django 5.2.11 on 2026-02-27 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_programexercise_name_ru_programexercise_reason_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='exerciselibrary',
            name='posture_tips',
            field=models.TextField(blank=True, help_text='AI-generated posture & technique tips'),
        ),
        migrations.AlterField(
            model_name='exerciselibrary',
            name='photo_url',
            field=models.URLField(blank=True, max_length=2000),
        ),
    ]
