# Generated by Django 5.2.11 on 2026-03-06 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0004_exerciselibrary_posture_tips_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogram',
            name='duration_weeks',
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name='workoutprogram',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
