# Generated by Django 5.2.11 on 2026-03-12 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0005_workoutprogram_duration_weeks_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='programday',
            name='name_en',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='workoutprogram',
            name='name_en',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
