# Generated by Django 5.2.11 on 2026-03-17 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_add_name_en_to_program_and_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='programday',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='workoutprogram',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='programexercise',
            name='confirmed',
            field=models.BooleanField(default=True),
        ),
    ]
