# Generated by Django 5.2.11 on 2026-03-17 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_programday_name_ru_workoutprogram_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutprogram',
            name='description_en',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='workoutprogram',
            name='nutrition_plan_en',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workoutprogram',
            name='shared_sections',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
