# Generated by Django 5.2.11 on 2026-03-19 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_add_warmup_cooldown_photo2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='E.g. "Muscle building — straight back teenager"', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Trainer notes: who this is for, goals, notes')),
                ('training_days', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='exerciselibrary',
            name='exercise_type',
            field=models.CharField(choices=[('main', 'Main Exercise'), ('warmup', 'Warm-up / Activation'), ('stretch', 'Stretch / Cool-down')], default='main', max_length=20),
        ),
        migrations.AlterField(
            model_name='exerciselibrary',
            name='photo_url',
            field=models.URLField(blank=True, help_text='Start position image', max_length=2000),
        ),
        migrations.CreateModel(
            name='ProgramTemplateDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField()),
                ('name', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, max_length=200)),
                ('warmup_data', models.JSONField(blank=True, null=True)),
                ('cooldown_data', models.JSONField(blank=True, null=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='programs.programtemplate')),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='ProgramTemplateExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.PositiveSmallIntegerField(default=3)),
                ('reps', models.CharField(default='10', max_length=20)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='programs.exerciselibrary')),
                ('template_day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='programs.programtemplateday')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
