import base64
import json
import mimetypes
import os

from django.conf import settings
import anthropic
import openai as _openai_mod


def generate_exercise_illustration(exercise_name, muscle_group, description=''):
    """
    Generate a cartoon female exercise illustration using DALL-E 3.
    Returns a URL string (hosted by OpenAI CDN, valid ~1 hour) or raises on error.
    Also returns posture tips generated by Claude Haiku.
    Returns dict: {image_url, posture_tips}
    """
    client_oai = _openai_mod.OpenAI(api_key=settings.OPENAI_API_KEY)
    client_ant = anthropic.Anthropic(api_key=settings.ANTHROPIC_API_KEY)

    prompt = (
        f"Flat-design cartoon illustration of a fit woman performing '{exercise_name}'. "
        f"Style: clean vector art, soft pastel colours, white background, similar to 30 Day Fitness app. "
        f"Show full body, correct exercise form, body in motion. "
        f"Highlight the {muscle_group} muscles with a warm accent colour. "
        f"No text, no labels, no equipment labels. Friendly, motivational look."
    )

    img_response = client_oai.images.generate(
        model='dall-e-3',
        prompt=prompt,
        size='1024x1024',
        quality='standard',
        n=1,
    )
    image_url = img_response.data[0].url

    # Generate posture tips with Claude Haiku
    tips_msg = client_ant.messages.create(
        model='claude-haiku-4-5-20251001',
        max_tokens=300,
        messages=[{
            'role': 'user',
            'content': (
                f"Give 3 concise posture & technique tips for '{exercise_name}' "
                f"(targets: {muscle_group}). Each tip max 12 words. "
                f"Format: numbered list 1. 2. 3. No intro text."
            ),
        }],
    )
    posture_tips = tips_msg.content[0].text.strip()

    return {'image_url': image_url, 'posture_tips': posture_tips}


def _format_goals(text):
    """Split numbered/bulleted goals into one-per-line format for the AI prompt."""
    import re
    if not text:
        return text
    # Split on patterns like "1." "2." "•" at word boundaries
    parts = re.split(r'\s*(?=(?:\d+\.|•)\s)', text)
    lines = [p.strip() for p in parts if p.strip()]
    return '\n'.join(lines) if len(lines) > 1 else text


def _encode_file(path):
    mime_type, _ = mimetypes.guess_type(path)
    if not mime_type:
        mime_type = 'application/octet-stream'
    with open(path, 'rb') as f:
        data = base64.standard_b64encode(f.read()).decode('utf-8')
    return data, mime_type


def _blood_test_block(student):
    """Return (content_blocks, attached_bool) for the blood test file.
    Handles both local storage and Cloudinary remote storage."""
    blocks = []
    if not student.blood_test_file:
        return blocks, False

    # Try local path first (development / local storage)
    try:
        path = student.blood_test_file.path
        if os.path.exists(path):
            data, mime_type = _encode_file(path)
            if mime_type == 'application/pdf':
                blocks.append({'type': 'document',
                               'source': {'type': 'base64', 'media_type': 'application/pdf', 'data': data}})
                return blocks, True
            elif mime_type.startswith('image/'):
                blocks.append({'type': 'image',
                               'source': {'type': 'base64', 'media_type': mime_type, 'data': data}})
                return blocks, True
    except Exception:
        pass

    # Fall back to remote URL (Cloudinary or any other remote storage)
    try:
        import httpx

        base_url = student.blood_test_file.url
        # Build candidate URLs to try: prefer raw/upload for non-image files
        urls_to_try = [base_url]
        if base_url and 'cloudinary.com' in base_url:
            if '/image/upload/' in base_url:
                urls_to_try.insert(0, base_url.replace('/image/upload/', '/raw/upload/'))
            elif '/raw/upload/' in base_url:
                urls_to_try.append(base_url.replace('/raw/upload/', '/image/upload/'))

        resp = None
        for url in urls_to_try:
            try:
                r = httpx.get(url, timeout=60, follow_redirects=True)
                if r.status_code == 200:
                    resp = r
                    break
            except Exception:
                continue

        if resp is None:
            return blocks, False

        content_type = resp.headers.get('content-type', '').split(';')[0].strip()
        if not content_type or content_type == 'application/octet-stream':
            ct, _ = mimetypes.guess_type(str(student.blood_test_file.name))
            content_type = ct or 'application/octet-stream'
        data = base64.standard_b64encode(resp.content).decode('utf-8')
        if content_type == 'application/pdf':
            blocks.append({'type': 'document',
                           'source': {'type': 'base64', 'media_type': 'application/pdf', 'data': data}})
            return blocks, True
        elif content_type.startswith('image/'):
            blocks.append({'type': 'image',
                           'source': {'type': 'base64', 'media_type': content_type, 'data': data}})
            return blocks, True
    except Exception:
        pass

    return blocks, False


def _parse_json(raw, msg=None):
    """Parse JSON from AI response. Uses json-repair to handle model quirks."""
    if msg is not None and getattr(msg, 'stop_reason', None) == 'max_tokens':
        raise ValueError(
            'AI response was cut off (too many blood markers or too large a document). '
            'Try uploading a shorter extract of the blood test.'
        )
    raw = raw.strip()
    if raw.startswith('```'):
        parts = raw.split('```')
        raw = parts[1]
        if raw.startswith('json'):
            raw = raw[4:]
        raw = raw.strip()
    try:
        return json.loads(raw)
    except json.JSONDecodeError:
        import re
        # Replace Python literals that are invalid JSON
        fixed = re.sub(r'\bNone\b', 'null', raw)
        fixed = re.sub(r'\bTrue\b', 'true', fixed)
        fixed = re.sub(r'\bFalse\b', 'false', fixed)
        try:
            return json.loads(fixed)
        except json.JSONDecodeError:
            # Last resort: full repair (handles trailing commas, missing quotes, etc.)
            from json_repair import repair_json
            return json.loads(repair_json(fixed))


def correct_text(text, field):
    """Rewrite health issues or goals in professional language."""
    client = anthropic.Anthropic(api_key=settings.ANTHROPIC_API_KEY)
    if field == 'health_issues':
        instruction = (
            'Ты — спортивный врач. Перепиши следующие жалобы/противопоказания клиента '
            'используя точную медицинскую и клиническую терминологию. '
            'Сохрани все факты дословно, только замени бытовые описания на профессиональные термины. '
            'Каждую жалобу/противопоказание выводи с новой строки в формате "• жалоба". '
            'Верни ТОЛЬКО список, без заголовков, без пояснений и без вступлений.'
        )
    else:
        instruction = (
            'Ты — профессиональный персональный тренер. Перепиши следующие пожелания клиента '
            'используя профессиональный язык спортивной науки и фитнеса. '
            'Сохрани суть пожеланий, сформулируй их как конкретные тренировочные цели. '
            'Каждую цель выводи с новой строки в формате "• цель" (через маркер •). '
            'Верни ТОЛЬКО список целей, без заголовков, без пояснений и без вступлений.'
        )
    msg = client.messages.create(
        model='claude-haiku-4-5-20251001',
        max_tokens=512,
        messages=[{'role': 'user', 'content': instruction + '\n\n' + text}],
    )
    return msg.content[0].text.strip()


def _normalize_health_issues(client, raw_text):
    """Rewrite health issues in professional medical/clinical language."""
    if not raw_text or not raw_text.strip():
        return raw_text
    msg = client.messages.create(
        model='claude-haiku-4-5-20251001',
        max_tokens=512,
        messages=[{
            'role': 'user',
            'content': (
                'Перепиши следующие жалобы/противопоказания клиента используя '
                'корректную медицинскую и клиническую терминологию. '
                'Сохрани все факты, добавь медицинские термины там, где это уместно. '
                'Верни ТОЛЬКО переписанный текст, без пояснений.\n\n'
                + raw_text
            ),
        }],
    )
    return msg.content[0].text.strip()


def suggest_nutrition(student, findings_summary=''):
    """Re-run only Call 2 (nutrition plan) for an existing program."""
    client = anthropic.Anthropic(api_key=settings.ANTHROPIC_API_KEY)

    age = student.age or 0
    gender = student.get_gender_display() if student.gender else 'Не указан'
    is_woman_40_plus = student.gender == 'F' and age >= 40

    health_issues = _normalize_health_issues(client, student.health_issues) or 'Не выявлено'

    profile = f"""Имя: {student.name}
Пол: {gender}
Возраст: {age if age else 'Не указан'}
Рост: {f'{student.height_cm} см' if student.height_cm else 'Не указан'}
Вес: {f'{student.weight_kg} кг' if student.weight_kg else 'Не указан'}
Цели:\n{_format_goals(student.goals) or 'Не указано'}
Проблемы со здоровьем / противопоказания: {health_issues}
Дополнительные заметки: {student.notes or 'Нет'}"""

    blood_blocks, blood_attached = _blood_test_block(student)

    hormone_note = ''
    if is_woman_40_plus:
        hormone_note = """
ОСОБЫЕ ИНСТРУКЦИИ — Женщина 40+:
- Проверить: эстроген, прогестерон, ФСГ, ЛГ, тестостерон, ДГЭА, ТТГ, Т3, Т4
- Костные маркеры: кальций, витамин D, ЩФ
- Включить силовые упражнения для укрепления костей
- Восстановление минимум 48ч между тренировками одних мышц
"""

    blood_note = (
        "Анализ крови прикреплён — учти данные при составлении плана питания."
        if blood_attached else
        "Анализ крови не загружен — рекомендации по профилю клиента."
    )

    prompt = f"""Ты — спортивный диетолог. Составь краткий план питания.

ПРОФИЛЬ:
{profile}
{hormone_note}
{blood_note}

ВЫВОДЫ: {findings_summary}

Верни ТОЛЬКО валидный JSON (без markdown):
{{
  "daily_calories": 2000,
  "macros": {{"protein_g": 150, "carbs_g": 200, "fat_g": 65}},
  "meals": [
    {{
      "meal": "Завтрак",
      "time": "7:00–8:00",
      "calories": 420,
      "foods": ["Овсянка 80г", "Яйца 2шт", "Банан 1шт"],
      "notes": ["Краткий совет макс 10 слов"]
    }}
  ],
  "fasting": {{
    "recommended": true,
    "type": "16:8",
    "eating_window": "12:00–20:00",
    "reasoning": ["Причина 1", "Причина 2"],
    "cautions": "Краткое предупреждение или пустая строка"
  }},
  "supplements": ["Витамин D 2000 МЕ", "Омега-3 1г"],
  "notes": [
    {{"title": "ГИДРАТАЦИЯ", "text": "Краткая рекомендация"}},
    {{"title": "ДЕФИЦИТ КАЛОРИЙ", "text": "Краткий расчёт"}}
  ]
}}

Правила (СТРОГО):
- Ровно 4 приёма пищи
- foods: 3–4 продукта с граммовкой
- notes каждого приёма: ровно 1 строка (массив из 1 элемента)
- fasting.reasoning: ровно 2 строки
- notes верхнего уровня: ровно 2 объекта
- Все строки — краткие (макс 15 слов)
"""

    content = blood_blocks + [{'type': 'text', 'text': prompt}]
    msg = client.messages.create(
        model='claude-sonnet-4-6',
        max_tokens=8096,
        messages=[{'role': 'user', 'content': content}],
    )
    return _parse_json(msg.content[0].text, msg)


def _build_exercise_menu(training_location):
    """Return a formatted string listing available exercises grouped by muscle group."""
    from programs.models import ExerciseLibrary
    if training_location == 'home':
        return """Место тренировки: ДОМА.
Используй ТОЛЬКО упражнения с собственным весом, гантелями или резиновыми лентами.
Примеры: Squat, Lunge, Glute Bridge, Hip Thrust (с гантелью), Push-up, Tricep Dip,
Dumbbell Row, Dumbbell Curl, Plank, Dead Bug, Mountain Climber, Jumping Jack,
Step-Up, Donkey Kick, Fire Hydrant, Romanian Deadlift (гантели), Lateral Raise (гантели).
Для поля "name" используй стандартные английские названия упражнений.
Также верни поле "muscle_group" для каждого упражнения (значения: glutes, legs, back, chest, shoulders, arms, core, cardio)."""

    # Gym — pull from actual library
    from collections import defaultdict
    groups = defaultdict(list)
    for ex in ExerciseLibrary.objects.all().order_by('muscle_group', 'name'):
        groups[ex.get_muscle_group_display()].append(ex.name)

    lines = ['Место тренировки: СПОРТЗАЛ.', 'Используй ТОЛЬКО упражнения из списка ниже (точные названия для поля "name"):']
    for group, names in sorted(groups.items()):
        lines.append(f'{group}: {", ".join(names)}')
    return '\n'.join(lines)


def suggest_program(student, training_days=3, training_location='gym'):
    """
    Two separate Claude calls to avoid hitting the output token limit:
      Call 1 → key_findings + workout days (exercises)
      Call 2 → nutrition plan
    """
    client = anthropic.Anthropic(api_key=settings.ANTHROPIC_API_KEY)

    age = student.age or 0
    gender = student.get_gender_display() if student.gender else 'Не указан'
    is_woman_40_plus = student.gender == 'F' and age >= 40

    health_issues = _normalize_health_issues(client, student.health_issues) or 'Не выявлено'

    profile = f"""Имя: {student.name}
Пол: {gender}
Возраст: {age if age else 'Не указан'}
Рост: {f'{student.height_cm} см' if student.height_cm else 'Не указан'}
Вес: {f'{student.weight_kg} кг' if student.weight_kg else 'Не указан'}
Дней тренировок в неделю: {training_days}
Цели:\n{_format_goals(student.goals) or 'Не указано'}
Проблемы со здоровьем / противопоказания: {health_issues}
Дополнительные заметки: {student.notes or 'Нет'}"""

    blood_blocks, blood_attached = _blood_test_block(student)

    hormone_note = ''
    if is_woman_40_plus:
        hormone_note = """
ОСОБЫЕ ИНСТРУКЦИИ — Женщина 40+:
- Проверить: эстроген, прогестерон, ФСГ, ЛГ, тестостерон, ДГЭА, ТТГ, Т3, Т4
- Костные маркеры: кальций, витамин D, ЩФ
- Включить силовые упражнения для укрепления костей
- Восстановление минимум 48ч между тренировками одних мышц
"""

    blood_note = (
        """Анализ крови прикреплён. Проанализировать:
- Анемия (Hb, ферритин, железо), воспаление (СРБ, СОЭ)
- Сахар/инсулинорезистентность (глюкоза, HbA1c)
- Печень/почки, гормоны, дефициты (D, B12, магний)
- Липиды (холестерин, триглицериды)"""
        if blood_attached else
        "Анализ крови не загружен — рекомендации по профилю клиента."
    )

    exercise_menu = _build_exercise_menu(training_location)

    home_muscle_group_field = (
        ',\n          "muscle_group": "glutes"'
        if training_location == 'home' else ''
    )

    # ── CALL 1: workout program + key findings ──────────────────────────────
    prompt1 = f"""Ты — профессиональный персональный тренер.
На основе профиля клиента{' и анализа крови' if blood_attached else ''} создай программу тренировок.

ПРОФИЛЬ:
{profile}
{hormone_note}
{blood_note}

ДОСТУПНЫЕ УПРАЖНЕНИЯ:
{exercise_menu}

═══════════════════════════════════════════
ОБЯЗАТЕЛЬНЫЕ ПРАВИЛА — НАРУШЕНИЕ НЕДОПУСТИМО:

1. АНАЛИЗ ЦЕЛЕЙ — ПЕРВЫЙ ШАГ:
   Внимательно прочитай цели клиента. Определи ПРИОРИТЕТНЫЕ мышечные группы.
   Пример: "похудеть ноги + увеличить ягодицы" → из {training_days} дней минимум 2 дня на ягодицы/ноги.
   Пример: "укрепить спину + рельеф рук" → приоритет спина и руки.

2. СТРОГОЕ СООТВЕТСТВИЕ ДНЯ И УПРАЖНЕНИЙ:
   Каждый день имеет ОДНУ тему (мышечную группу или комбинацию).
   ВСЕ упражнения дня должны тренировать ТОЛЬКО указанные в названии дня мышцы.
   ЗАПРЕЩЕНО: добавлять упражнения на плечи в день ног, руки в день спины и т.д.
   Допустимо: в конце дня 1–2 упражнения на пресс/кардио как финишёр.

3. ВОЗРАСТ И ЗДОРОВЬЕ:
   Возраст {age} лет — адаптируй нагрузку и выбор упражнений.
   Противопоказания: {health_issues} — исключи упражнения, создающие нагрузку на указанные области.

4. ТОЛЬКО УПРАЖНЕНИЯ ИЗ СПИСКА (для зала):
   Поле "name" должно совпадать с названиями из списка выше ТОЧНО.
═══════════════════════════════════════════

Отвечай ТОЛЬКО валидным JSON (без markdown, без пояснений):
{{
  "program_name": "Название программы на русском",
  "key_findings": [
    "Одно предложение — главная цель клиента и фокус программы",
    "Одно предложение — почему выбрано такое распределение дней под цели клиента",
    "Одно предложение — возрастные/физические адаптации в программе",
    "Одно предложение — ключевая находка из анализа крови (если есть)",
    "Одно предложение — рекомендация по восстановлению и прогрессии"
  ],
  "days": [
    {{
      "day_number": 1,
      "day_name": "День 1 — Ягодицы и ноги",
      "exercises": [
        {{
          "name": "Barbell Hip Thrust",
          "name_ru": "Тяга бедра со штангой",
          "sets": 3,
          "reps": "10-12",
          "reason_ru": "Почему это упражнение важно для ДАННОГО клиента"{home_muscle_group_field}
        }}
      ]
    }}
  ]
}}

Правила:
- Ровно {training_days} дней в "days"
- 4–6 упражнений в день
- "name" — английское название из списка доступных упражнений
- "name_ru" — русское название
- key_findings — каждый элемент это ОДНО предложение
- Если анализ крови загружен — включи реальные числовые значения в findings
"""

    content1 = blood_blocks + [{'type': 'text', 'text': prompt1}]
    msg1 = client.messages.create(
        model='claude-sonnet-4-6',
        max_tokens=8096,
        messages=[{'role': 'user', 'content': content1}],
    )
    result = _parse_json(msg1.content[0].text, msg1)

    # ── CALL 2: nutrition plan ───────────────────────────────────────────────
    findings_summary = ' '.join(result.get('key_findings', []))
    prompt2 = f"""Ты — спортивный диетолог. Составь краткий план питания.

ПРОФИЛЬ:
{profile}
{hormone_note}
{blood_note}

ВЫВОДЫ: {findings_summary}

Верни ТОЛЬКО валидный JSON (без markdown):
{{
  "daily_calories": 2000,
  "macros": {{"protein_g": 150, "carbs_g": 200, "fat_g": 65}},
  "meals": [
    {{
      "meal": "Завтрак",
      "time": "7:00–8:00",
      "calories": 420,
      "foods": ["Овсянка 80г", "Яйца 2шт", "Банан 1шт"],
      "notes": ["Краткий совет макс 10 слов"]
    }}
  ],
  "fasting": {{
    "recommended": true,
    "type": "16:8",
    "eating_window": "12:00–20:00",
    "reasoning": ["Причина 1", "Причина 2"],
    "cautions": "Краткое предупреждение или пустая строка"
  }},
  "supplements": ["Витамин D 2000 МЕ", "Омега-3 1г"],
  "notes": [
    {{"title": "ГИДРАТАЦИЯ", "text": "Краткая рекомендация"}},
    {{"title": "ДЕФИЦИТ КАЛОРИЙ", "text": "Краткий расчёт"}}
  ]
}}

Правила (СТРОГО):
- Ровно 4 приёма пищи
- foods: 3–4 продукта с граммовкой
- notes каждого приёма: ровно 1 строка (массив из 1 элемента)
- fasting.reasoning: ровно 2 строки
- notes верхнего уровня: ровно 2 объекта
- Все строки — краткие (макс 15 слов)
"""

    content2 = blood_blocks + [{'type': 'text', 'text': prompt2}]
    msg2 = client.messages.create(
        model='claude-sonnet-4-6',
        max_tokens=8096,
        messages=[{'role': 'user', 'content': content2}],
    )
    nutrition = _parse_json(msg2.content[0].text, msg2)
    result['nutrition'] = nutrition

    return result


def analyze_blood_test(student):
    """
    Deep standalone analysis of a blood test file.
    Returns structured JSON with every marker, deficiencies, and exercise/nutrition recommendations.
    Returns None if no blood test file is attached or the file cannot be read.
    """
    client = anthropic.Anthropic(api_key=settings.ANTHROPIC_API_KEY, timeout=240.0)

    blood_blocks, blood_attached = _blood_test_block(student)
    if not blood_attached:
        return None

    age = student.age or 0
    gender = student.get_gender_display() if student.gender else 'Не указан'
    is_woman_40_plus = student.gender == 'F' and age >= 40

    profile = f"""Имя: {student.name}
Пол: {gender}
Возраст: {age if age else 'Не указан'}
Рост: {f'{student.height_cm} см' if student.height_cm else 'Не указан'}
Вес: {f'{student.weight_kg} кг' if student.weight_kg else 'Не указан'}
Цели: {student.goals or 'Не указано'}
Проблемы со здоровьем / противопоказания: {student.health_issues or 'Не указано'}"""

    hormone_note = ''
    if is_woman_40_plus:
        hormone_note = """
ВАЖНО — Женщина 40+: особое внимание уделить гормональному статусу.
Проверить: эстроген, прогестерон, ФСГ, ЛГ, тестостерон, ДГЭА, ТТГ, Т3, Т4.
Костные маркеры: кальций, витамин D, щелочная фосфатаза.
"""

    prompt = f"""Ты — спортивный врач и клинический диетолог. Проанализируй анализ крови клиента.

ПРОФИЛЬ КЛИЕНТА:
{profile}
{hormone_note}

Верни ТОЛЬКО валидный JSON (без markdown, без пояснений):
{{
  "summary": "2–3 предложения — общее состояние здоровья и главные выводы",
  "markers": [
    {{
      "name": "Гемоглобин",
      "value": "115 г/л",
      "reference": "120–160 г/л",
      "status": "low",
      "interpretation": "Лёгкая анемия — снижает выносливость"
    }},
    {{
      "name": "Глюкоза",
      "value": "4.8 ммоль/л",
      "status": "normal"
    }}
  ],
  "deficiencies": [
    {{
      "nutrient": "Железо",
      "severity": "moderate",
      "impact_on_training": "Быстрая утомляемость, медленное восстановление",
      "food_sources": ["Говядина 150г", "Шпинат 100г", "Чечевица 200г"],
      "supplement": "Феррум Лек 100 мг/день с едой, 3 месяца"
    }}
  ],
  "exercise_recommendations": [
    "Конкретная рекомендация по тренировкам"
  ],
  "nutrition_recommendations": [
    "Конкретная рекомендация по питанию с продуктами"
  ],
  "urgent_attention": [],
  "positive_findings": [
    "Что в норме — мотивирует клиента"
  ]
}}

Правила:
- markers: ДВА формата:
  * АНОМАЛЬНЫЕ (low/high/critical_low/critical_high): name + value + reference + status + interpretation (макс 10 слов)
  * НОРМАЛЬНЫЕ: name + value + status — БЕЗ reference и interpretation
- status: "normal" | "low" | "high" | "critical_low" | "critical_high"
- Учитывай половые нормы и возраст {age} лет
- deficiencies: только реальные дефициты (low/critical_low)
- exercise_recommendations: 3–4 пункта
- nutrition_recommendations: 3–4 пункта с продуктами и граммовкой
- urgent_attention: только КРИТИЧЕСКИ важные значения (пустой массив если нет)
- positive_findings: 2–3 пункта
"""

    content = blood_blocks + [{'type': 'text', 'text': prompt}]
    msg = client.messages.create(
        model='claude-sonnet-4-6',
        max_tokens=8096,
        messages=[{'role': 'user', 'content': content}],
    )
    return _parse_json(msg.content[0].text, msg)
