# Generated by Django 5.2.11 on 2026-04-30 18:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('programs', '0010_exercise_type_and_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExerciseDemo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_start', models.ImageField(blank=True, null=True, upload_to='exercise_demos/')),
                ('image_mid', models.ImageField(blank=True, null=True, upload_to='exercise_demos/')),
                ('prompt_used', models.TextField(blank=True)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('exercise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo', to='programs.exerciselibrary')),
            ],
        ),
    ]
