# Generated by Django 5.2.11 on 2026-05-01 23:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_exercisedemo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='independentmember',
            name='plan',
            field=models.CharField(choices=[('free', 'Free'), ('pro', 'Pro')], default='free', max_length=10),
        ),
        migrations.AddField(
            model_name='independentmember',
            name='stripe_customer_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='independentmember',
            name='stripe_subscription_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='independentmember',
            name='subscription_current_period_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='independentmember',
            name='subscription_status',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.CreateModel(
            name='TrainerBilling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free (up to 3 clients)'), ('growing', 'Growing ($20/mo)'), ('unlimited', 'Unlimited ($50/mo)')], default='free', max_length=20)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=100)),
                ('stripe_subscription_id', models.CharField(blank=True, max_length=100)),
                ('subscription_status', models.CharField(blank=True, max_length=30)),
                ('subscription_current_period_end', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='trainer_billing', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
